# Generated by Django 2.0.1 on 2018-01-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('info', models.TextField()),
                ('download', models.FileField(blank=True, upload_to='document/s')),
            ],
        ),
    ]
